# https://github.com/raghur/mermaid-filter
# --toc
# -V toc-title:"Inhaltsverzeichnis"
pdf:
	pandoc README.md \
	   -o 01.pdf  \
	   -F mermaid-filter \
	   -V papersize:a4 \
	   --highlight-style pygments
